var constants = {
  ADD_TODO: "ADD_TODO",
  TOGGLE_TODO: "TOGGLE_TODO",
  CLEAR_TODOS: "CLEAR_TODOS",
  DELETE_TODO: "DELETE_TODO",
  LOAD_TODOS: "LOAD_TODOS",
  UNDO_TODOS: "UNDO_TODOS"
};

module.exports = constants;
